spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/citron
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        default_schema: public
  main:
    allow-bean-definition-overriding: true

  data:
    elasticsearch:
      client:
        rest:
          uris: http://localhost:9200
      repositories:
        enabled: true
